name: Sync any artifact from tenant

on:
  workflow_dispatch:
    inputs:
      packageId:
        description: 'Package ID'
        required: true
      directory:
        description: 'Target artifact directory (relative from Git repository root)'
        required: false
      includedIds:
        description: 'Included Ids (optional)'
        required: false
      excludedIds:
        description: 'Excluded Ids (optional)'
        required: false
      draft:
        description: 'Draft handling'
        type: choice
        options:
          - SKIP
          - ADD
          - ERROR
        required: false
      dirNaming:
        description: 'Naming convention for artifact directories'
        required: false
        type: choice
        options:
          - ID
          - NAME
      syncPackageDetails:
        description: "Sync package details"
        type: boolean
        required: false
      message:
        description: 'Commit message (optional)'
        required: false
jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:latest

    steps:
    - uses: actions/checkout@v4

    - name: 'Sync any artifact'
      uses: engswee/flashpipe-action/sync@v1
      with:
        # tmn-host: trial-d6guw7gv.integrationsuite-trial.cfapps.ap21.hana.ondemand.com
        tmn-host: trial-d6guw7gv.it-cpitrial03.cfapps.ap21.hana.ondemand.com
        oauth-host: trial-d6guw7gv.authentication.ap21.hana.ondemand.com
       # oauth-tokenurl: https://trial-d6guw7gv.authentication.ap21.hana.ondemand.com/oauth/token
        oauth-clientid: ${{ secrets.DEV_CLIENT_ID }}
        oauth-clientsecret: ${{ secrets.DEV_CLIENT_SECRET }}
        package-id: ${{ github.event.inputs.packageId }}
        dir-artifacts-relative: ${{ github.event.inputs.directory }}
        dir-naming-type: ${{ github.event.inputs.dirNaming }}
        draft-handling: ${{ github.event.inputs.draft }}
        ids-include: ${{ github.event.inputs.includedIds }}
        ids-exclude: ${{ github.event.inputs.excludedIds }}
        git-commit-msg: ${{ github.event.inputs.message }}
        sync-package-details: ${{ github.event.inputs.syncPackageDetails }}
